### ISSUE TITLE
Topic02_Functional_Programming/functional-style-习题三

### ISSUE THREAD

**Issue by Eric7Lau** [Kivy-CN/Duke-STA-663-CN#2]
小白请教个问题，习题3这里对alist使用append追加元素后为什么会改变全局环境中的alist?
原题代码为：
```python
x = 5
def f(alist): 
    for i in range(x): 
        alist.append(i) 
    return alist 
alist = [1,2,3] 
ans = f(alist)
print ans 
print alist # alist has been changed!
##输出结果
#[1, 2, 3, 0, 1, 2, 3, 4] 
#[1, 2, 3, 0, 1, 2, 3, 4] 
```
我把它改成下面这样后就不会改变了。这是因为上面的函数使用了append方法的原因吗？
```python
x = 5
def f(alist=None):
    if alist is None:
        alist = [] 
    alist = alist + [i for i in range(x)] 
    return alist 
alist = [1,2,3] 
ans = f(alist) 
print ans 
print alist 
###输出结果如下###
#[1, 2, 3, 0, 1, 2, 3, 4] 
#[1, 2, 3]
```

**Comment by wizardforcel** [comment]
append 会改变数组内容，加法运算不会。

**Comment by howard-hou** [comment]
你可以用这个工具visualize python,一步一步的看一看，python内部到底在做什么。
http://pythontutor.com/visualize.html#mode=edit <http://pythontutor.com/visualize.html#mode=edit>
append是直接在原list空间操作，这个空间同时指向alist和ans
加法赋值后，开辟了新的空间：

> 在 2017年4月26日，下午9:27，Eric7Lau <notifications@github.com> 写道：
> 
> x = 5
> def f(alist=None):
>     if alist is None:
>         alist = [] 
>     alist = alist + [i for i in range(x)] 
>     return alist 
> alist = [1,2,3] 
> ans = f(alist) 
> print ans 
> print alist

**Comment by Eric7Lau** [comment]
终于明白了！谢谢！

**Comment by Eric7Lau** [comment]
> 你可以用这个工具visualize python,一步一步的看一看，python内部到底在做什么。
> http://pythontutor.com/visualize.html#mode=edit <http://pythontutor.com/visualize.html#mode=edit>
> append是直接在原list空间操作，这个空间同时指向alist和ans
> 加法赋值后，开辟了新的空间：

终于明白了！谢谢！

**Comment by Eric7Lau** [comment]
> append 会改变数组内容，加法运算不会。

谢谢！
